import "./global.css";
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Nunito } from "next/font/google";
import TanstackProvider from "@_providers/TanstackProvider";
import { RTOProviders } from "@_providers/RTOProviders";
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

const inter = Inter({ subsets: ["latin"] });

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Flowerstore | Rider App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
        <body className={nunito.className}>
          <TanstackProvider>
            <RTOProviders>
              {children}
              <ToastContainer />
            </RTOProviders>
          </TanstackProvider>
        </body>
      </html>
  );
}
