import "./global.css";
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Nunito } from "next/font/google";
import TanstackProvider from "@_providers/TanstackProvider";

const inter = Inter({ subsets: ["latin"] });

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Flowerstore | Rider App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <TanstackProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </TanstackProvider>
  );
}
